spring.application.name=aura

spring.security.user.name=rakshi
spring.security.user.password =Java


#the database url
spring.datasource.url=jdbc:postgresql://localhost:5432/aura
spring.datasource.username=postgres
spring.datasource.password=rakshith


# Tells Hibernate to automatically create/update database tables
spring.jpa.hibernate.ddl-auto=update

# Shows generated SQL in console (great for debugging!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensures dialect matches PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect